const undertakingCredits = `Generated by the ACM-X Undertaking Generator v0.2.0
Copyright FEU Tech ACM Student Chapter. All rights reserved.

Contributors (ACM App Team):

- Sir Jeneffer Sabonsolin  :  Adviser             :  https://www.linkedin.com/in/jeneffer-sabonsolin-70320329a
- Csypress Ornos           :  President           :  https://www.linkedin.com/in/csypres-ornos-148528287
- Alpha Romer Coma         :  Software Developer  :  https://www.linkedin.com/in/alpharomercoma
- Rab Karl Colasino        :  Webmaster           :  https://www.linkedin.com/in/mr-colasino

For further information, please contact us at <acm.feu.it@gmail.com>`;

export default undertakingCredits;
