const undertakingCredits = `Generated by the ACM-X Undertaking Generator v0.2.0
Copyright FEU Tech ACM Student Chapter. All rights reserved.

Contributors (ACM App Team):

- Sir Abraham Magpantay   :  Adviser             :  https://www.facebook.com/aber.magpantay
- Jericho Menguito        :  President           :  https://www.facebook.com/JMENGUITO28
- Cyril Reigine Paruli    :  Vice President      :  https://www.linkedin.com/in/cyrilreigineparuli
- Guennevere Rito         :  Project Manager     :  https://www.linkedin.com/in/guennevere-rito-990256255
- Alpha Romer Coma        :  Software Developer  :  https://www.linkedin.com/in/alpharomercoma
- Emily Tan Sanchez       :  Branding Officer    :  https://www.facebook.com/francischuegan
- Francis Chuegan         :  Branding Officer    :  https://www.facebook.com/emilyats

For further information, please contact us at <acm.feu.it@gmail.com>`;

export default undertakingCredits;
