const undertakingCredits = `Generated by the ACM-X Undertaking Generator v0.1.0
Copyright FEU Tech ACM Student Chapter. All rights reserved.

Contributors (ACM App Team):

- Sir Abraham Magpantay   :  Adviser
- Jericho L. Menguito     :  President
- Cyril Reigine Paruli    :  Vice President
- Guennevere Rito         :  Project Manager/QA
- Alpha Romer Coma        :  Software Developer/Webmaster
- Emily Tan Sanchez       :  UI/UX Designer
- Francis Chuegan         :  UI/UX Designer

For further information, please contact us at <acm.feu.it@gmail.com>`;

export default undertakingCredits;
